version: '3.8'

services:
  backend:
    # build: .
    image: backend:v1
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydatabase
      - DB_HOST=db
    # env_file:
    #   - .env

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  postgres_data:
