apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: myapp
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: mydatabase