apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: vinsensiusf/demo-fe:v4
          ports:
            - containerPort: 8081
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://backend-service.myapp.svc.cluster.local:8080"
