apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: myapp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data/postgres"
    type: DirectoryOrCreate
