apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: myapp
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=    # "postgres" (Base64 encoded)
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # "postgres" (Base64 encoded)
  POSTGRES_DB: dG9kb3M=            # "todos" (Base64 encoded)
